name: Example Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment type'
        default: Sandbox

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Print environment variable
        run: |
          echo "Environment type : ${{ github.event.inputs.environment }}"
