name: Example Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment type'
        default: Sandbox

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment variable
        run: |
          echo "Environment type : ${{ github.event.inputs.environment }}"
