name: Github Sandbox Environment Variable Test Suite

on:
  workflow_dispatch:
    inputs:
      environment:
        default: "Sandbox"
  push:
    branches:
      - '*'  # This triggers the workflow on every branch
  
jobs:
  test:
    name: Run Action To Validate Environment Variables
    runs-on: ubuntu-latest
    steps:
      - name: Verifiy Environment Variable Value
        run: |
          echo "Application Log Level: ${{ inputs.environment.vars.APPLICATION_LOG_LEVEL }}"
          echo "System Log Level: ${{ inputs.environment.vars.SYSTEM_LOG_LEVEL }}"
