name: Django Test Suite with Coverage

on:
  push:
    branches:
      - '*'  # This triggers the workflow on every branch

env:
  APPLICATION_LOG_LEVEL: ${{ vars.APPLICATION_LOG_LEVEL }}
  SYSTEM_LOG_LEVEL: ${{ vars.SYSTEM_LOG_LEVEL }}
  
jobs:
  test:
    name: Run Action To Validate Environment Variables
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  

      - name: Verifiy Environment Variable Value
        run: |
          echo "${{ env.APPLICATION_LOG_LEVEL }}"
          echo "${{ env.SYSTEM_LOG_LEVEL }}"

    
