name: Github Sandbox Environment Variable Test Suite

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        default: Sandbox
        required: true
        type: string
  push:
    branches:
      - '*'  # This triggers the workflow on every branch
  
jobs:
  test:
    name: Run Action To Validate Environment Variables
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Verifiy Environment Variable Value
        run: |
          echo "Environment: ${{ inputs.environment }}"
          echo "Application Log Level: ${{ vars.APPLICATION_LOG_LEVEL }}"
          echo "System Log Level: ${{ vars.SYSTEM_LOG_LEVEL }}"
